version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-04-07T05-28-58Z
    command: server --console-address ":9001" /data
    networks:
      - minio
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    networks:
      - minio
    volumes:
      - "./nginx/${MINIO_PROTOCOL}.conf.template:/etc/nginx/templates/minio.conf.template"
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    depends_on:
      - minio
    environment:
      MINIO_HOSTNAME: ${MINIO_HOSTNAME}
      MINIO_CONSOLE_HOSTNAME: ${MINIO_CONSOLE_HOSTNAME}

networks:
  minio:
    driver: bridge